export FABRIC_CREDMGR_HOST='cm.fabric-testbed.net'
export FABRIC_ORCHESTRATOR_HOST='orchestrator.fabric-testbed.net'
export FABRIC_BASTION_HOST="bastion-1.fabric-testbed.net"

# Set your Bastion username and private key
export FABRIC_BASTION_USERNAME="kthare10_0011904101"
export FABRIC_BASTION_KEY_LOCATION="/root/kthare10/fabric-bastion"
export FABRIC_TOKEN_LOCATION="/root/kthare10/tokens.json"

# Set the keypair FABRIC will install in your slice.
export FABRIC_SLICE_PRIVATE_KEY_FILE="/root/kthare10/fabric-slivers"
export FABRIC_SLICE_PUBLIC_KEY_FILE="/root/kthare10/fabric-slivers.pub"